### ISSUE TITLE
Named Strongs can be nested

### ISSUE THREAD

**Issue by MaxMatti** [basicpp/basicpp17#13]
Not sure if this is intended, but the following code compiles (on clang 8.0.0) even though I would expect it to throw an error at line 12.

    #include <meta17/Type.h>
    #include <strong17/Strong.opaque.h>
    #include <strong17/Strong.trait.h>

    #include <utility>

    using strong17::Strong;

    STRONG_OPAQUE_TYPE(MyOpaqueStrong, Strong<int>);

    void testFunction() {
        using ThisShouldNotWork = Strong<MyOpaqueStrong>;
        ThisShouldNotWork tmp;
    }

**Comment by strfry** [comment]
Commit  65e8ed36cbe703f2df1c45d7cdaaba6f3e9d7cf8 contains a solution inspired by https://stackoverflow.com/a/30991097

**Comment by arBmind** [comment]
@strfy please add a test for the fix… I doubt that this works as expected.

**Comment by strfry** [comment]
@arBmind Done in c20904687b28ddb3e38620d4f3e081efce6d0ea8
Previously i just tested it locally, because i didn't realize how i had to use SFINAE to test the failing case...
And yes, i was just as surprised that this works ;)

**Comment by arBmind** [comment]
With 2e85cae2c28ff336aac2d378fc4ccadc5dc41601 this seems to be fixed in a different way, that really works and is tested.
