### ISSUE TITLE
Usability of Tuple constructors

### ISSUE THREAD

**Issue by strfry** [basicpp/basicpp17#17]
Assume a Tuple of different type

    using Aggregate = Tuple<A, B, C>;

The generated Tuple offers 2 relevant kind of constructors:

     b) Aggregate(C{}, B{}, A{}) // Same number of arguments, but in arbitrary order

     a) Aggregate(Tuple{B{}, A{}}) // construct from lesser Tuple, also arbitrary order

a) makes it very difficult to read from the compiler errors, because it has a complicated SFINAEd signature that doesn't allow the compiler to display a simple type conversion error.
MSVC doesn't even bother to list the failed candidates, and just gives the dreaded "Can't convert initializer list..." error.
The current resolution to this case would be `Aggregate{Tuple{A, B}}`, leaning on Tuple's type deduction guide, to first construct an appropriate "lesser tuple".

I also argue that reordering argument reordering, and argument omission are convenience features intended for test case construction, and belong together.

Also, only one of these conveniences (the re-ordering) is duplicated in both implementations,
and in both cases obstruct proper constructor argument related error messages.

Related to #9 and #12

**Comment by arBmind** [comment]
@strfry I agreed that this is an issue, we should solve.

Maybe I missed it - but do you have an idea how to improve the situation? - remove a constructor? convert them to a static factory function?
